# Generated by Django 4.2.10 on 2024-02-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thriller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThrillerMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(verbose_name='Release Date')),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_py.thriller')),
            ],
        ),
        migrations.CreateModel(
            name='ScifiMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(verbose_name='Release Date')),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_py.scifi')),
            ],
        ),
        migrations.CreateModel(
            name='HorrorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(verbose_name='Release Date')),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_py.horror')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(verbose_name='Release Date')),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_py.action')),
            ],
        ),
    ]
