# Generated by Django 4.2.10 on 2024-02-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_py', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(verbose_name='Release Date')),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_py.genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='actionmovie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='horrormovie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='scifimovie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='thrillermovie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionMovie',
        ),
        migrations.DeleteModel(
            name='Horror',
        ),
        migrations.DeleteModel(
            name='HorrorMovie',
        ),
        migrations.DeleteModel(
            name='Scifi',
        ),
        migrations.DeleteModel(
            name='ScifiMovie',
        ),
        migrations.DeleteModel(
            name='Thriller',
        ),
        migrations.DeleteModel(
            name='ThrillerMovie',
        ),
    ]
